version: '3'

services:
  redis:
    image: redis
    ports:
      - 6379:6379

  shulkerbox:
    depends_on:
      - redis
    build:
      context: .
      dockerfile: backend.dockerfile

    command: uvicorn main:app --host 0.0.0.0
    volumes:
      - .:/app
    ports:
      - 8000:8000